title: "Rubin Hood"
description: "© 2025 Rubin-Hood"
theme: minima
plugins:
  - jekyll-feed


navigation:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: My Projects
    url: /projects/
